# Revive configuration for Utify

# Enable rules
[rules]
# Enforces comments on exported types/functions/consts
[rules.exported]

# Warn if function parameters are unused
[rules.unused-parameter]

# Warn if variable names are too short
[rules.var-naming]

# Warn for long lines
[rules.line-length]
arguments = [120]